### ISSUE TITLE
Question: definition of event systems

### ISSUE THREAD

**Issue by nanonull** [c0ffeeartc/EntitasGenericAddon#1]
Hey!

There are the following system class names in Readme in Events examples:
EventSystem_Any_Flag2
EventSystem_Any_Removed2

Right now this classes should be created manually? Is there some naming convention(is it used by reflection)?

**Comment by c0ffeeartc** [comment]
Hello.
Reflection happens only during initialisation stage once, after that there is no reflection used.

These systems are generic, they are already defined and ready to be created with `new`, manually add them to Systems for each needed component:
```csharp
// Step 2. Add event systems to Systems. This step could be automated in future
    systems.Add( new EventSystem_Any2<Game, CompB>(  ) );
    systems.Add( new EventSystem_Any_Removed2<Game, CompB>(  ) );  // Removed
    systems.Add( new EventSystem_Any_Flag2<Game, FlagA>(  ) );  // Flag, callback on True and False unlike original EventsFeature
```

**Comment by c0ffeeartc** [comment]
Forgot to answer about naming convention.

Class names do not affect reflection, name them whatever you like in your project.

In this project I try to keep the most abstract info about the class on the left side, and add more concrete details on the right side connecting by underscore `_`, it's similar to how namespaces work, or dot `.` operator for classes and it's inner parts. Sometimes at the beginning can be name of the feature combining classes by name into logical feature group.

Sometimes I don't follow convention and make mistakes, be careful XD.

**Comment by nanonull** [comment]
EventV2 systems are neat!
