### ISSUE TITLE
Question: does it make sense to add support for struct flag components?

### ISSUE THREAD

**Issue by nanonull** [c0ffeeartc/EntitasGenericAddon#2]
...since 'new struct' is more efficient than 'new class()' (they said 8 times faster https://medium.com/csharp-architects/whats-faster-in-c-a-struct-or-a-class-99e4761a7b76)

Is it good idea to have struct flag component?
![image](https://user-images.githubusercontent.com/8210414/98462176-e5533000-21ba-11eb-92cc-517eaf23d654.png)

From another point of view - Entitas will pool class-flag components anyway, so it needs some perf. tests to compare time.

**Comment by c0ffeeartc** [comment]
Under the hood all components are classes. Struct components are wrapped inside `StructComponent<TData>` class in `Data` field https://github.com/c0ffeeartc/EntitasGenericAddon/blob/master/Entitas.Generic/Core/StructComponent.cs

If I recall correctly reason is to avoid boxing and to be compatible with vanilla Entitas. Entitas keeps `List<IComponent>` to store components in various places, using structs directly would bring boxing/unboxing problem. 
The speed improvement "8 times faster" should be backed up with tests in concrete example, it would be great to get such performance boost. In current implementation both struct and class are very close in performance.

**Comment by nanonull** [comment]
StructComponent makes sense. Thanks for answer!
